### ISSUE TITLE
update readme with info on uploading with gsutil

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/pangeo-AMPS#1]
4e5e8e1273de1b3e99e1e326197105ee7b517300 does this, but I opened this issue to have somewhere to make sure @sashamontelli and I understand this.

**Comment by jkingslake** [comment]
thanks @porterdf for the new readme. 
What is the benefit of using rsync in this case? Just because it allows to you to select files by similar filenames?

**Comment by porterdf** [comment]
Not necessary, but in this particular use case I prefer `rsync` along with gsutil - I sometimes use the 'synchronize' aspect of it, but more so for its restart capability which can help when issuing large transfers from an HPC to a Cloud, remotely.  `cp` of course works fine, and also capable of parallel streams with gsutil - pick your poison.
